TOOLPATH=../../../tools/
include ../../config.txt

default:
	$(MAKE) -C console
	$(MAKE) -C message
	$(MAKE) -C fullscreen

clean:
	$(MAKE) -C console clean
	$(MAKE) -C message clean
	$(MAKE) -C fullscreen clean
