TOOLPATH=../../../tools/
include ../../config.txt

default:
	$(MAKE) -C graphic
	$(MAKE) -C desktop
	$(MAKE) -C sheet

clean:
	$(MAKE) -C graphic clean
	$(MAKE) -C desktop clean
	$(MAKE) -C sheet clean
