TOOLPATH=../../../tools/
include ../../config.txt

default:
	$(MAKE) -C string
	$(MAKE) -C sprintf
	$(MAKE) -C math
	$(MAKE) -C data_structures

clean:
	$(MAKE) -C string clean
	$(MAKE) -C sprintf clean
	$(MAKE) -C math clean
	$(MAKE) -C data_structures clean