TOOLPATH=../../../tools/
include ../../config.txt

default:
	$(MAKE) -C io
	$(MAKE) -C mouse
	$(MAKE) -C keyboard
	$(MAKE) -C timer
	$(MAKE) -C buzzer
	$(MAKE) -C hd
	$(MAKE) -C cmos
	$(MAKE) -C com
	$(MAKE) -C lpt
	$(MAKE) -C fpu
	$(MAKE) -C cpu
	$(MAKE) -C pci

clean:
	$(MAKE) -C io clean
	$(MAKE) -C mouse clean
	$(MAKE) -C keyboard clean
	$(MAKE) -C timer clean
	$(MAKE) -C buzzer clean
	$(MAKE) -C hd clean
	$(MAKE) -C cmos clean
	$(MAKE) -C com clean
	$(MAKE) -C lpt clean
	$(MAKE) -C fpu clean
	$(MAKE) -C cpu clean
	$(MAKE) -C pci clean