TOOLPATH=../../../tools/
include ../../config.txt

default:
	$(MAKE) -C io
	$(MAKE) -C mouse
	$(MAKE) -C keyboard
	$(MAKE) -C timer
	$(MAKE) -C buzzer
	$(MAKE) -C hd
	$(MAKE) -C cmos

clean:
	$(MAKE) -C io clean
	$(MAKE) -C mouse clean
	$(MAKE) -C keyboard clean
	$(MAKE) -C timer clean
	$(MAKE) -C buzzer clean
	$(MAKE) -C hd clean
	$(MAKE) -C cmos clean